imdb/imdb/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('movies/', include('movies.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

imdb/movies/urls.py
from django.urls import path
from . import views

app_name = 'movies'
urlpatterns = [
    path('', views.index, name='index'),
    path('<slug:slug>/', views.show, name='show'),
    path('genres/<slug:slug>/', views.genre, name='genre')
]

imdb/movies/models.py
from django.db import models
from django.utils.text import  Truncator

class Movie(models.Model):
    genres = models.ManyToManyField('movies.genre', related_name='movies', blank=True)
    peoples = models.ManyToManyField('peoples.people', through='peoples.moviepeople', related_name='movies')
    title = models.CharField(max_length=120)
    slug = models.SlugField(max_length=120, unique=True)
    excerpt = models.CharField(max_length=120)
    cover = models.ImageField(upload_to='covers', null=True)
    description = models.TextField()
    release_date = models.DateField()
    duration_time = models.DurationField(null=True)

    def __str__(self):
        return self.title

    @property
    def converted_duration_time(self):
        return '{:02d}h {:02d}m'.format(*divmod(self.duration_time.seconds, 60))

    @property
    def truncated_excerpt(self):
        return Truncator(self.excerpt).chars(100)

class Genre(models.Model):
    name = models.CharField(max_length=120)
    slug = models.SlugField(max_length=120)

    def __str__(self):
        return self.name

imdb/peoples/models.py
from django.db import models

from movies.models import Movie

class People(models.Model):
    first_name = models.CharField(max_length=64)
    second_name = models.CharField(max_length=64)
    born_date = models.DateField()
    born_place = models.CharField(max_length=120)

    def __str__(self):
        return self.first_name + ' ' + self.second_name

    @property
    def full_name(self):
        return self.first_name + ' ' + self.second_name

class MoviePeople(models.Model):
    people = models.ForeignKey('peoples.people', on_delete=models.CASCADE, related_name='movie_people')
    movie = models.ForeignKey('movies.movie', on_delete=models.CASCADE, related_name='movie_people')
    movie_name = models.CharField(max_length=120, blank=True)
    type = models.ForeignKey('peoples.peopletype', on_delete=models.CASCADE, related_name='+')

    def __str__(self):
        return self.movie.title + ' - ' + self.people.full_name + ' - ' + self.movie_name

class PeopleType(models.Model):
    name = models.CharField(max_length=64)

    def __str__(self):
        return self.name

imdb/movies/views.py
from django.shortcuts import get_list_or_404, get_object_or_404, render
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

from .models import Movie

def index(request):
    movies_list = Movie.objects.all();
    counter_movies = movies_list.count

    paginator = Paginator(movies_list, 12)
    page = request.GET.get('page')
    movies = paginator.get_page(page)

    return render(request, 'movies/index.html', {
            'movies': movies,
            'counter_movies': counter_movies
    })

def show(request, slug):
    movie = get_object_or_404(Movie, slug=slug)

    return render(request, 'movies/show.html', {
        'movie': movie
    })

def genre(request, slug):
    genres_list = Movie.objects.filter(genres__slug=slug)
    counter_movies = genres_list.count

    paginator = Paginator(genres_list, 12)
    page = request.GET.get('page')
    genres = paginator.get_page(page)

    return render(request, 'movies/genre.html', {
        'genres': genres,
        'counter_movies': counter_movies
    })

imdb/peoples/views.py
from django.shortcuts import render

# Create your views here.

imdb/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="pl" dir="ltr">
<head>
    <meta charset="utf-8">
    <title>{% block title %}{% endblock title %}</title>

    <!-- Compiled and minified CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0-beta/css/materialize.min.css">
    <link rel="stylesheet" href="{% static 'css/app.css' %}" />
</head>
<body>
    <header>
        <nav>
            <div class="nav-wrapper">
                <a href="#!" class="brand-logo"><img src="{% static 'images/logo.jpg' %}" class="logo" /></a>
                <ul class="right hide-on-med-and-down">
                    <li><a href="#">Main page</a></li>
                    <li><a href="sass.html">Find</a></li>
                    <li><a href="{% url 'movies:index' %}">Movies</a></li>
                    <li><a href="#">Actors</a></li>
                    <li><a href="#">Wishlist</a></li>
                </ul>
            </div>
        </nav>
    </header>

    <main>
        <div class="container">
            {% block content %}
            {% endblock content %}
        </div>
    </main>

    <footer class="page-footer">
        <div class="container">
            <div class="row">
                <div class="col l6 s12">
                    <h5 class="white-text">Footer Content</h5>
                    <p class="grey-text text-lighten-4">You can use rows and columns here to organize your footer content.</p>
                </div>
                <div class="col l4 offset-l2 s12">
                    <h5 class="white-text">Links</h5>
                    <ul>
                        <li><a class="grey-text text-lighten-3" href="#!">Link 1</a></li>
                        <li><a class="grey-text text-lighten-3" href="#!">Link 2</a></li>
                        <li><a class="grey-text text-lighten-3" href="#!">Link 3</a></li>
                        <li><a class="grey-text text-lighten-3" href="#!">Link 4</a></li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="footer-copyright">
            <div class="container">
                © 2014 Copyright Text
                <a class="grey-text text-lighten-4 right" href="#!">More Links</a>
            </div>
        </div>
    </footer>

    <!-- JSScripts -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0-beta/js/materialize.min.js"></script>
    <script src="{% static 'js/app.js' %}"></script>
</body>
</html>

imdb/templates/movies/genre.html
{% extends "base.html" %}
{% load static %}

{% block title %}
Movies
{% endblock title %}

{% block content %}
<h4>We have in our database {{counter_movies}} movie{{counter_movies|pluralize}}</h4>
<div class="row">
    {% for movie in genres %}
    <div class="col s12 m4">
        <div class="card hoverable">
            <div class="card-image">
                <img src="{{ movie.cover.url}}">
                <span class="card-title">{{movie.title}}</span>
            </div>
            <div class="card-content">
                <small><span title="Released">{{movie.release_date}}</span>, <span title="Duration">{{movie.converted_duration_time}}</span></small>
                <p>
                    {{movie.truncated_excerpt}}
                </p>
                <p style="margin-top: 20px;">
                    Genres: <small>
                        {% for genre in movie.genres.all %}
                            <a href="{% url 'movies:genre' genre.slug %}">{{genre.name}},</a>
                        {% endfor %}
                    </small>
                </p>
            </div>
            <div class="card-action right-align blue-grey darken-3">
                <a href="{% url 'movies:show' movie.slug %}">Check movie</a>
            </div>
        </div>
    </div>
    {% empty %}
    <div class="s12">
        <h3>Any movie was not add.</h3>
    </div>
    {% endfor %}
</div>
<ul class="pagination">
    {% if genres.has_previous %}
        <li class="waves-effect"><a href="?page=1">&laquo; first</a></li>
        <li class="waves-effect"><a href="?page={{ genres.previous_page_number }}">previous</a></li>
    {% endif %}

        <li class="active"><a href="#!">Page {{ genres.number }} of {{ genres.paginator.num_pages }}.</a></li>

    {% if genres.has_next %}
        <li class="waves-effect"><a href="?page={{ genres.next_page_number }}">next</a></li>
        <li class="waves-effect"><a href="?page={{ genres.paginator.num_pages }}">last &raquo;</a></li>
    {% endif %}
  </ul>
{% endblock content %}

imdb/templates/movies/index.html
{% extends "base.html" %}
{% load static %}

{% block title %}
Movies
{% endblock title %}

{% block content %}
<h4>We have in our database {{counter_movies}} movie{{counter_movies|pluralize}}</h4>
<div class="row">
    {% for movie in movies %}
    <div class="col s12 m4">
        <div class="card hoverable">
            <div class="card-image">
                <img src="{{ movie.cover.url}}">
                <span class="card-title">{{movie.title}}</span>
            </div>
            <div class="card-content">
                <small><span title="Released">{{movie.release_date}}</span>, <span title="Duration">{{movie.converted_duration_time}}</span></small>
                <p>
                    {{movie.truncated_excerpt}}
                </p>
                <p style="margin-top: 20px;">
                    Genres: <small>
                        {% for genre in movie.genres.all %}
                            <a href="{% url 'movies:genre' genre.slug %}">{{genre.name}},</a>
                        {% endfor %}
                    </small>
                </p>
            </div>
            <div class="card-action right-align blue-grey darken-3">
                <a href="{% url 'movies:show' movie.slug %}">Check movie</a>
            </div>
        </div>
    </div>
    {% empty %}
    <div class="s12">
        <h3>Any movie was not add.</h3>
    </div>
    {% endfor %}
</div>
<ul class="pagination">
    {% if movies.has_previous %}
        <li class="waves-effect"><a href="?page=1">&laquo; first</a></li>
        <li class="waves-effect"><a href="?page={{ movies.previous_page_number }}">previous</a></li>
    {% endif %}

        <li class="active"><a href="#!">Page {{ movies.number }} of {{ movies.paginator.num_pages }}.</a></li>

    {% if movies.has_next %}
        <li class="waves-effect"><a href="?page={{ movies.next_page_number }}">next</a></li>
        <li class="waves-effect"><a href="?page={{ movies.paginator.num_pages }}">last &raquo;</a></li>
    {% endif %}
  </ul>
{% endblock content %}

imdb/templates/movies/show.html
{% extends "base.html" %}
{% load static %}

{% block title %}
Movies
{% endblock title %}

{% block content %}

<div class="card horizontal">
    <div class="card-image">
        <img src="{{ movie.cover.url}}" style="max-width: 100%; height: auto;">
    </div>
    <div class="card-stacked">
        <div class="card-content">
            <h3 style="margin-top: 0;">{{movie.title}}</h3>
            <small>{{movie.release_date}}, {{movie.converted_duration_time}}</small>
            <p>
                {{movie.description}}
            </p>
            <p style="margin-top: 20px;">
                Genres: <small>
                    {% for genre in movie.genres.all %}
                        <a href="{% url 'movies:genre' genre.slug %}">{{genre.name}},</a>
                    {% endfor %}
                </small>
            </p>
        </div>
        <div class="card-action">
            <a href="#">This is a link</a>
        </div>
    </div>
</div>

{% endblock content %}